#cloud-config
package_update: true
package_upgrade: true

runcmd:
  - echo "Installing Python and Pip..."
  - apt install -y python3 python3-pip
  - pip install --upgrade pip
  - echo "Installing LangChain..."
  - pip install langchain

  - echo "Installing Docker..."
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - systemctl start docker
  - systemctl enable docker

  - echo "Running Flowise in Docker..."
  - docker run -d -p 3000:3000 --name flowise flowiseai/flowise

  - echo "Installing NGINX..."
  - apt install -y nginx
  - systemctl start nginx
  - systemctl enable nginx

  - echo "Installation Completed Successfully!"
